Update byobu; fix for BYOBU_RUN_DIR error
❯ byobu-config
Traceback (most recent call last):
  File "/home/daniel/.dotfiles/lib/byobu/usr/bin/byobu-config", line 63,
  in <module>
      RELOAD_FLAG = "%s/reload-required" % (BYOBU_RUN_DIR)
      NameError: name 'BYOBU_RUN_DIR' is not defined